### PR TITLE
feat: add combinations_with_replacement

### PR DESCRIPTION
**Pull request by tommilligan**
As part of a personal project, I wanted to generate combinations of a set `n` of length `k`, but where elements may be repeated (i.e. may be present more than once in the output). I was not able to find an implementation of this in Rust anywhere - please correct me if I'm wrong!

The `CombinationsWithReplacement` iterator consumes a given `Iterator` of `Clone`-able items, and yields combinations of type `Vec<I::Item>` (the same api as `Combinations`). Suggestions for a more concise name welcome.

The algorithm is based on [this Stackoverflow question](https://stackoverflow.com/questions/127704/algorithm-to-return-all-combinations-of-k-elements-from-n) and [sample C code](https://stackoverflow.com/questions/561/how-to-use-combinations-of-sets-as-test-data#794)

### CODE REVIEW

**Comment by tommilligan** [comment]
Ping @jswrenn @phimuemue for review or suggestions

**Comment by jswrenn** [comment]
Thanks for the contribution! My major point of reluctance in merging this is that it's not lazy: calling `combinations_with_replacement` on a cyclic iterator will never produce a new iterator. There's a strong expectation that iterator adaptors are lazy (and `Combinations` is) and that merely constructing them isn't a linear time operation.

**Comment by tommilligan** [comment]
Good point, didn't consider this as it doesn't really make sense to get combinations for an infinite iterator. However I take your point, I've:
- moved `LazyBuffer` to it's own module
- updated `CombinationsWithReplacement` to use `LazyBuffer` internally
- added tests for using infinite iterators with `combinations` and `combinations_with_replacement` adaptors

**Comment by jswrenn** [comment]
Looks good! Thanks!

bors r+

**Comment by tommilligan** [comment]
It should, but it built successfully in CI with `cargo build --verbose --no-default-features`. I'm not sure why it wasn't caught.

**Comment by jswrenn** [comment]
Well spotted, @pczarn. I'm not sure why this passed the CI, either. I'm tied up preparing for a conference right now, so I won't be able to investigate this for about another week, unfortunately.

**Comment by tommilligan** [comment]
@pczarn I've just double checked the diff, and it is marked as `#[cfg(feature = "use_std")]` everywhere I can see - possibly just a GitHub UI issue yesterday? Unless you can point me at a specific line, I don't see anything that's incorrect.

**Comment by pczarn** [comment]
It's fine - I viewed a single commit instead of the entire diff.

**Pull request merged**
