### PR TITLE
prepare v0.12.0 release

### PR DESCRIPTION
**Pull request by jswrenn**
UPDATE: Changelog complete! 

~Still need to write changelog.~ Is there any way to easily get all PRs merged after a date/tag? Running this:
```
git log v0.11.0.. --reverse --merges --oneline --grep='Merge #' | cut -d' ' -f3 | sort -n
```
Only turned up merge commits for:
- #709
- #713
- #715
- #718
- #723
- #727
- #735
- #737
- #739
- #745

But we have plenty more PRs that were merged without merge commits: https://github.com/rust-itertools/itertools/milestone/5?closed=1

I'm quite tempted to adopt a squash-before-merging approach before our next release to simplify this (so we could just list off all commits without too much noise).

### CODE REVIEW

**Comment by Philippe-Cholet** [comment]
`git` is an awesome command line tool but it can't have all the informations that github has. So I would look at the github API instead. ...Merged PRs since 2023-06-22 (date for v0.11.0):
- Web search: https://github.com/search?q=repo:rust-itertools/itertools+type:pr+merged:>2023-06-22
- The same in JSON: https://api.github.com/search/issues?q=repo:rust-itertools/itertools+type:pr+merged:>2023-06-22&per_page=100
- With `curl` and `jq`, assuming there are less than 100 results (there are 52 today), the entire list is:
`curl -H "Accept: application/vnd.github+json" https://api.github.com/search/issues?q=repo:rust-itertools/itertools+type:pr+merged:>2023-06-22&per_page=100 | jq ".items[].number"`
The json data holds way more informations such as `jq ".items[].pull_request.merged_at"` that could help sort them but I only knew about `jq` before this.

**Comment by jswrenn** [comment]
Thanks! Coming at this from a slightly different angle, running this:
```
git log v0.11.0.. --reverse --oneline \
  | cut -d' ' -f1 \
  | xargs -I {} gh pr list --search {} --state merged --json number \
  | jq '.[] | .number' \
  | sort -nu
```
...gives:
- #602
- #709
- #713
- #715
- #716
- #718
- #719
- #720
- #723
- #724
- #727
- #729
- #732
- #734
- #735
- #736
- #737
- #738
- #739
- #744
- #745
- #746
- #748
- #751
- #752
- #753
- #754
- #760
- #761
- #763
- #765
- #770
- #772
- #773
- #774
- #775
- #777
- #778
- #780
- #782
- #785
- #786
- #787
- #789
- #790
- #793
- #794
- #795
- #796
- #797
- #799
- #800

...which is also 52 PRs! That sounds about right. I'll start putting together the changelog.

**Comment by Philippe-Cholet** [comment]
I dived into `jq` to nicely sort merged PRs by the `merged_at` key and came with two git aliases:

	pulls-after-date = "!f() { curl -H 'Accept: application/vnd.github+json' 'https://api.github.com/search/issues?per_page=100&q=repo:rust-itertools/itertools+type:pr+merged:>'$1 | jq '.items | sort_by(.pull_request.merged_at) | .[].number'; }; f"
	pulls-after-tag = "!f() { git pulls-after-date $(git log -1 --format=%as $1); }; f"
    # %aI would be more precise than %as but it contains a "+" that messes with the github url.

Usage: `git pulls-after-date 2023-06-22` or simply `git pulls-after-tag v0.11.0`.

**Review by phimuemue — APPROVED** [review]
Thanks for this. Looks good to me.

**Comment by Philippe-Cholet** [comment]
@jswrenn There is `#![doc(html_root_url = "https://docs.rs/itertools/0.11/")]` in `lib.rs`.

**Comment by jswrenn** [comment]
Whoops, I thought we deleted that.

**Pull request merged**
