### PR TITLE
Add try_collect method to Itertools

### LINKED ISSUE #359: Feature request: try_collect
I often find myself wanting to write

```rust
some_iter
    .map(Type::fallible_conversion)
    .collect()?
```

This requires a turbofish for `collect` though, because both `?` and `collect` are generic. In every case I've had, I wanted the `FromIterator` implementation for `Result`. A dedicated `try_collect` method that's only available for `Result` iterators would solve this.

### PR DESCRIPTION
**Pull request by jplatte**
fixes #359

### CODE REVIEW

**Comment by jswrenn** [comment]
Can you elaborate the documentation with a doctest code example?

**Comment by jplatte** [comment]
@jswrenn Done! :)

**Comment by jplatte** [comment]
CI is now fixed.

**Comment by jswrenn** [comment]
Thanks!

bors r+

**Pull request merged**
