### PR TITLE
build: enforce formatting

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
Could anyone please approve workflow, just for the purpose of seeing it fail?

**Comment by mightyiam** [comment]
Rebased. Please approve workflow and review.

**Comment by mightyiam** [comment]
Oh, and we did confirm enforcement works (the first commit) in [this run](https://github.com/rust-itertools/itertools/actions/runs/6058972895).

**Comment by mightyiam** [comment]
Unsurprisingly, the checks passed. There is no good time to merge this. It may upset contributors with open pull requests. There are 40 open pull requests. Yet, that number might not decrease. Therefore, it may never be less painful than now to merge this. And it's only a click away! :shipit: :wink:

**Comment by Philippe-Cholet** [comment]
@mightyiam There was a recent _important_ discussion about enforcing formatting anyway in #702 (that and **more...**). I guess it's currently delayed the time to try to implement some RFC.

**Comment by mightyiam** [comment]
Thanks. Let us know here, as soon as we can pull the trigger on this. The first commit is the enforcement part. The second is merely the result of `$ cargo fmt`.

**Comment by Philippe-Cholet** [comment]
#744 bumped actions/checkout to v4, I guess you might want to do the same.

**Comment by mightyiam** [comment]
Thank you. Done.

**Comment by jswrenn** [comment]
Thank you! I'm closing this in favor of #751 (which is just a replay of the commits), for reasons explained there.

**Pull request closed without merging**
