### PR TITLE
0.8.1 release

### PR DESCRIPTION
**Pull request by danielhenrymantilla**
Updated Changelog and `Cargo.toml` for the ~~0.9.0~~ 0.8.1 release, as suggested in https://github.com/rust-itertools/itertools/pull/366#issuecomment-545172659

  - [Rendered](https://github.com/rust-itertools/itertools/blob/a7a1203960451fe2ba21394e5b38981ef8323181/README.rst)

### CODE REVIEW

**Comment by bluss** [comment]
Nice going. do you know if it needs to be a breaking update?

**Comment by danielhenrymantilla** [comment]
You're right, I overlooked that, reverting back to `0.8.1`

**Comment by tobz1000** [comment]
`.combinations` isn't new; I think I just updated the documentation and made a trivial code change.

**Comment by danielhenrymantilla** [comment]
Seems I misread the commit history; will fix that tomorrow.

**Comment by jswrenn** [comment]
Thank you, @danielhenrymantilla! I've published to crates.io.

**Pull request merged**
