### PR TITLE
Give `take_while_inclusive` a more intuitive doc alias

### PR DESCRIPTION
**Pull request by Ciel-MC**
I could not for the life of me find this function lmao, it's called take until most places so I think an alias for searchability would be nice

### CODE REVIEW

**Review by Philippe-Cholet — APPROVED** [review]
It seems reasonable to me.

However, there is [`Iterator::take_while`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.take_while) so it does not come from nowhere. 😀

**Comment by Philippe-Cholet** [comment]
@Ciel-MC Maybe `#[doc(alias = "TakeUntil")]` on `TakeWhileInclusive`?

**Comment by jswrenn** [comment]
Seems reasonable to me!

**Comment by Ciel-MC** [comment]
> However, there is [`Iterator::take_while`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.take_while) so it does not come from nowhere. 😀

I do understand that it didn't come from nowhere, but it is a bit like calling 2 "1+1", like yes it came from adding 1 to 1, but it has a pretty common name already.

> @Ciel-MC Maybe `#[doc(alias = "TakeUntil")]` on `TakeWhileInclusive`?

I mean, I guess that is just as searchable? Though I'm not sure why you'd want it on the struct instead of the method(excuse my inexperience with api design)

**Comment by Philippe-Cholet** [comment]
It was a question. After searching doc aliases on rust-lang/rust, it sure does not alias structs much if at all, my bad.

**Pull request merged**
