### PR TITLE
Remove unused macro variant

### PR DESCRIPTION
**Pull request by phimuemue**
I'd like to try bors with that one.

### CODE REVIEW

**Comment by jswrenn** [comment]
[Criterion strikes again!](https://travis-ci.org/github/rust-itertools/itertools/jobs/692920021) (Or, rather, a dependency of it.)

Perhaps we could add a `bench` default feature, and only pull `criterion` if that feature is present. Then, we modify our CI to use `--no-default-features` for the MSRV build.

**Comment by phimuemue** [comment]
Ah, I see.

I think your Idea is good, even though I have no experience in crate features. And while skimming https://doc.rust-lang.org/cargo/reference/features.html#rules, I read 

> Dev-dependencies cannot be optional.

I am not sure if this affects us.

**Pull request merged**
