### PR TITLE
GroupMap: add fold_with (2) more generic init

### PR DESCRIPTION
**Pull request by phimuemue**
Hi, this completes #778 

@Philippe-Cholet Could you please approve this? Apparently I cannot simply push anymore to the repo.

@jswrenn I ran into this problem twice now. Am I doing something wrong? Is there a way to allow fixups like this for maintainers?

### CODE REVIEW

**Comment by tamird** [comment]
It seems a bit strange to accept the value since init is only called for the first key-value pair in a group. The value that the closure will be called with is not guaranteed to be deterministic AFAIK.

**Comment by Philippe-Cholet** [comment]
@tamird I agree it's weird to add the `value` parameter, I'm not fond of it. But I guess it's not a big pain to ignore it by adding `,_` to the closure. And maybe there is an usage for it.

@phimuemue Can't you approve them yourself? In the "Files changed" page: click "Review changes" button, check "Approve" box, valid by clicking "Submit review" button. That's what I would do. I'd like to know where you are blocked if you are.

**Comment by phimuemue** [comment]
@Philippe-Cholet I already tried this. "Approve" is disabled (seems I cannot review my own PRs).

**Comment by phimuemue** [comment]
> It seems a bit strange to accept the value since init is only called for the first key-value pair in a group. The value that the closure will be called with is not guaranteed to be deterministic AFAIK.

True, but `fold_with` is merely a shorthand that avoids `Option`s. `val` is deterministic: the iterator's first item associated with its key.

**Review by Philippe-Cholet — APPROVED** [review]

**Comment by Philippe-Cholet** [comment]
@phimuemue I previously successfully merged two PRs (by approving) that I did not create but where I committed to. I guess the key point is that you created the PR.

**Pull request merged**
