### PR TITLE
Use criterion for benchmarking

### PR DESCRIPTION
**Pull request by orium**
Not only is it a better benchmark tool, it also avoids depending on nightly rustc.

### CODE REVIEW

**Comment by orium** [comment]
The build is failing because travis also tests with rust 1.24, where `dyn Trait` was not yet stable.  That if a fairly old release.  I will bump the minimum rust version to 1.27.  Let me know if that is not ok.

**Comment by orium** [comment]
This should be merged after #392, since that PR is also getting rid of `try!()`.

**Comment by jswrenn** [comment]
Thanks! Could you fix that merge conflict? I'll merge this ASAP once you do.

**Comment by orium** [comment]
Done :slightly_smiling_face:

**Comment by jswrenn** [comment]
Thanks!

bors r+

**Pull request merged**
