### PR TITLE
feat(`FilterMapOk`): implement `DoubleEndedIterator`

### PR DESCRIPTION
**Pull request by Xenira**
`DoubleEndedIterator` implementation for `FilterMapOk` analog to #948.

Hope `rev()` is the right thing here, as `rfind_map` does not exist (#949).

Refs: #947

### CODE REVIEW

**Review by Philippe-Cholet — APPROVED** [review]
You did not need to make a merge commit.

`.by_ref().rev().find_map(` is verbose but it's not unprecedented like for `Unique::next_back` and it's fine.

**Comment by Xenira** [comment]
> You did not need to make a merge commit.

Wanted to rebase, but messed up. Like my pr's to be up to date :)

**Comment by Philippe-Cholet** [comment]
No prob, the commit history is not that clean anyway.

**Comment by Xenira** [comment]
Benchmarked against the `filter_map` variant and its mostly in noise threshold. (2 cases 2% faster but I guess, thats because different base load on my system).

The `rev()` is more readable though.

**Pull request merged**
